# Repaso Pandas 2

## Ejercicio 1

1. Lee, en un DataFrame llamado ``df``, el archivo CSV de la liga que tienes en esta misma carpeta
2. Elimina la columna "Unnamed: 0" y muestra las 10 primeras filas

In [1]:
import pandas as pd

## Ejercicio 2

1. ¿Cuántas temporadas (season) diferentes hay? ¿Cuáles?
2. ¿Cuántas jornadas (round)?
3. Obtén todos los equipos que han participado en LaLiga durante las temporadas que se muestran en el DataFrame. ¿Cuántos han sido?

## Ejercicio 3

Ahora empieza lo divertido:
1. Filtra el df para quedarte con la última temporada disponible.
2. Recrea la tabla final de la temporada donde deberás recoger:
  - Equipo
  - Goles totales marcados
  - Goles totales recibidos
  - Diferencia de goles
  - Partidos ganados
  - Partidos perdidos
  - Partidos empatados
  - Puntos

3. Ordena la tabla para recrear las posiciones finales de los equipos

4. Asegúrate que el Equipo aparece como una columna y que el índice del DataFrame refleja la posición en la que han quedado

Leyenda:
  - LGAF: Local Goles A Favor
  - LGEC: Local Goles En Contra
  - VGAF: Visitante Goles A Favor
  - VGEC: Visitante Goles En Contra
  - GTAF: Goles Totales A Favor
  - GTEC: Goles Totales En Contra
  
  - LG: Local partidos Ganados
  - LE: Local partidos Empatados
  - LP: Local partidos Perdidos
  - VG: Visitante partidos Ganados
  - VE: Visitante partidos Empatados
  - VP: Visitante partidos Perdidos
  - G: Total partidos Ganados
  - E: Total partidos Empatados
  - P: Total partidos Perdidos
  
  
  - PTS: Puntos

,localTeam,LGAF,LGEC,VGAF,VGEC,GTAF,GTEC,LG,LE,LP,VG,VE,VP,V,E,P,PTS
Posición,,,,,,,,,,,,,,,,,
0,Barcelona,53,11,46,18,99,29,16,3,0,12,6,1,28,9,1,93
1,Atletico de Madrid,30,8,28,14,58,22,12,6,1,11,4,4,23,10,5,79
2,Real Madrid,54,20,40,24,94,44,12,4,3,10,6,3,22,10,6,76
3,Valencia,36,16,29,22,65,38,13,3,3,9,4,6,22,7,9,73
4,Villarreal,35,22,22,28,57,50,11,3,5,7,4,8,18,7,13,61
5,Betis,35,31,25,30,60,61,10,4,5,8,2,9,18,6,14,60
6,Sevilla,31,22,18,36,49,58,11,5,3,6,2,11,17,7,14,58
7,Getafe,26,13,16,20,42,33,9,4,6,6,6,7,15,10,13,55
8,Girona,26,22,24,37,50,59,8,3,8,6,6,7,14,9,15,51
9,Eibar,26,19,18,31,44,50,8,4,7,6,5,8,14,9,15,51
10,Espanol,20,16,16,26,36,42,8,6,5,4,7,8,12,13,13,49
11,Real Sociedad,47,29,19,30,66,59,10,3,6,4,4,11,14,7,17,49
12,Celta de Vigo,34,23,25,37,59,60,8,8,3,5,2,12,13,10,15,49
13,Alaves,21,23,19,27,40,50,9,1,9,6,1,12,15,2,21,47
14,Levante,25,28,19,30,44,58,7,6,6,4,7,8,11,13,14,46
15,Atletico de Bilbao,19,16,22,33,41,49,6,8,5,4,5,10,10,13,15,43
16,Leganes,19,19,15,32,34,51,9,4,6,3,3,13,12,7,19,43
17,Deportivo,22,33,16,43,38,76,4,6,9,2,5,12,6,11,21,29
18,Las Palmas,15,38,9,36,24,74,4,2,13,1,5,13,5,7,26,22
19,Malaga,14,27,10,34,24,61,4,3,12,1,2,16,5,5,28,20

## Ejercicio 4

Crea una función a partir de lo anterior para que reciba un parámetro season (con valores como los de la columna 'season') y sea capaz de devolver la tabla de clasificación tal cuál haya quedado.

Utiliza esta función para calcular los descendidos por cada season

## Ejercicio 5

Analicemos ahora un poco los datos de la última temporada (puedes ayudarte de la tabla de clasificación generada)::

1. ¿Qué equipos han descendido?
2. ¿Cuáles han entrado en Champions (4 primeros)? ¿Quién ha ganado?
3. ¿Cuál ha sido el equipo más goleador? ¿Y el más goleado?
4. ¿Cuál ha sido el equipo que menos goles ha encajado?
5. ¿Cuáles han sido las medias de goles recibidos por equipo? ¿Y de goles marcados?
6. ¿Qué equipo le ha sacado más rendimiento a los goles? Es decir, ¿qué equipo ha conseguido más puntos/gol?
7. ¿Y cuál ha sido el que menos lo ha rentabilizado?
8. ¿Cuál ha sido la media de anotación de todos los partidos? Saca el valor tanto para todos los resultados como para locales y visitantes

## Ejercicio 6

Analicemos ahora el dataset original (puedes utilizar la función creada anteriormente):

1. ¿Qué temporada se han marcado más goles en total?
2. ¿Cuál es el equipo que más goles ha marcado en todas estas temporadas?
3. ¿Cuál es la media anotadora de Mayo? ¿Y de Diciembre?
4. ¿En qué jornada de todas las temporadas se han marcado más goles? ¿Cuántos?
5. ¿En qué jornada de todas las temporadas se han marcado menos goles? ¿Cuántos?
6. ¿Cuál ha sido la season con más goles? ¿Y la que menos?